import axios from "axios";

import { API_URL } from "../appSecrets.ts";

const VibifyAPI = () => {
    
    /**
     * Acquire a CSRF token generated by the server and set the
     * appropriate Axios defaults, including the token header.
     */
    async function acquireCsrfToken() {
        const response = await axios.get(API_URL + 'get_csrf_token/');

        axios.defaults.xsrfCookieName = 'csrftoken';
        axios.defaults.xsrfHeaderName = 'X-CSRFToken';
        axios.defaults.headers.common['X-CSRFToken'] = response.data['csrfToken'];
        axios.defaults.headers.withXSRFToken = true;
        axios.defaults.withCredentials = true;
    }

    return { acquireCsrfToken };
}

export default VibifyAPI;